### ISSUE TITLE
Run two boxes

### ISSUE THREAD

**Issue by matejkramny** [YungSang/boot2docker-vagrant-box#10]
I am using this box to make services available..
They span across 2 projects, so 2 vagrant machines are created (simultaneously)

It makes vagrant complain though, because it is trying to expose the docker port, which is already exposed by the first box.

Is it possible to tell vagrant to not expose the port?

Thanks :)

**Comment by YungSang** [comment]
Hi @matejkramny ,

The default setting in the box is the following.

```
config.vm.network :forwarded_port, guest: 2375, host: 2375
```

But you can override it in your Vagrantfile as below to use more than one instance at once.

```
config.vm.network :forwarded_port, guest: 2375, host: 2375, auto_correct: true
```

Please see also my sample Vagrantfile which I have already commented it in.
https://vagrantcloud.com/yungsang/boxes/boot2docker

**Comment by matejkramny** [comment]
I missed the `auto_correct: true` :P.

Thanks!

**Comment by YungSang** [comment]
You're welcome.
