### ISSUE TITLE
Can you increase the disk from 40 GB to 200 GB.

### ISSUE THREAD

**Issue by amiorin** [YungSang/boot2docker-vagrant-box#15]
I need more space.

Thx

**Comment by YungSang** [comment]
Let me see... Please let me think for a while.
I can increase a disk space, but I would like to know the side effects first. 
Is there any way to increase a disk using `VBoxMange` after `vagrant up`?

**Comment by YungSang** [comment]
It seems no side effects at all.

In the other hand,
Packer generates VDMK with OVF in a box, so it's not easy to increase the VDMK.
I will try another way to create VDI instead of VDMK without Packer.

**Comment by YungSang** [comment]
Anyway I will try to close this issue by the next release.

**Comment by YungSang** [comment]
It seems no luck for VDI.
virtualbox.org • View topic - export VM using VDI instead of VMDK
https://forums.virtualbox.org/viewtopic.php?f=1&t=58460

**Comment by YungSang** [comment]
@amiorin
I found an articles "Increasing a Boot2Docker volume - Docker Documentation".
https://docs.docker.com/articles/b2d_volume_resize/
It also can be used for my box.

**Comment by YungSang** [comment]
I found an another way to resize the disk easily and made a script for it.
https://github.com/YungSang/boot2docker-vagrant-box/blob/resizable/contrib/resize4docker

Usage: resize4docker [Vagrant Machine Name] [Size in MB]
- `Vagrant Machine Name`: the name of the machine which has a disk to resize. The default is "default" as Vagrant, or you can find at `config.vm.define "<name>"` in Vagrantfile.
- `Size in MB`: the number of the resized disk size. If omit, it will just replace VMDK with VDI.

So you can resize it to any size you want to expand.

**Comment by amiorin** [comment]
Thx

**Comment by amiorin** [comment]
I decided to add a second disk.

``` ruby
 config.vm.provider "virtualbox" do |v|
    file = "box-disk2.vdi"
    v.customize ["createhd", "--filename", file, "--size", "#{ 200 * 1000 }"]
    v.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file]
end
```

**Comment by YungSang** [comment]
@amiorin Thank you for the information. That's much better.
