### ISSUE TITLE
Persist data between box restarts?

### ISSUE THREAD

**Issue by michaelshobbs** [YungSang/boot2docker-vagrant-box#16]
First off, thank you for putting this vagrant box together. It's been quite helpful.

I noticed at some point between 1.3.0 and 1.3.4, my postgres data was not being persisted between restarts. (i.e. `vagrant halt && vagrant up --provision`) I should also mention that I use a docker volume to persist data outside the container to `/mnt/sda/var/lib/postgresql/data`.

Where would you recommend I mount the postgres volume so that I can persist the data between restarts? Is this not possible anymore?

Any guidance would be greatly appreciated.

**Comment by YungSang** [comment]
I'm sorry that I didn't realize that.
Since v1.3.2, the persist data disk has been changed `/mnt/sda` to `/mnt/sda1` due to fixing 42 layers issue of AUFS.

**Comment by michaelshobbs** [comment]
Makes sense. Thanks for the clarification.
