### ISSUE TITLE
Unable to mount nfs folder

### ISSUE THREAD

**Issue by nireak** [YungSang/boot2docker-vagrant-box#4]
Hi
On $ vagrant up when mounting NFS folders I get the following error

==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.56.0:'/Users/nireak/Documents/VBoxData' /data

Stdout from the command:

Stderr from the command:

mount: RPC: Unable to send; errno = Permission denied
mount: mounting 192.168.56.0:/Users/nireak/Documents/VBoxData on /data failed: Bad file descriptor

I'm using OS X 10.9.2, Vagrant 1.6.3, and your box versions 0.12.0 and also 0.9.3

Thank you for your help

**Comment by YungSang** [comment]
Hi @nireak,
I have never experienced that on my side with the same versions as yours.
Could you provide your Vagrantfile, just in case?

**Comment by YungSang** [comment]
@nireak 
I guess that `/Users/nireak/Documents/VBoxData` is not within the current folder where you execute `vagrant up`.

**Comment by nireak** [comment]
@YungSang 
Thanks for your assistance
My VagrantFile is located at /Users/nireak/Dropbox/projects/Vagrants/test

....the contents are based on the sample you kindly provided...
If have changed the network to match my vb
config.vm.network "private_network", ip: "192.168.56.10" to match my host-only network at VBox (192.168.56.0)

also /etc/exports shows
'# VAGRANT-BEGIN: 501 ac5b2706-6ca2-45b8-94ad-3d5bfc4151e0
"/Users/nireak/Dropbox/projects/Vagrants/test" 192.168.56.10 -alldirs -mapall=501:20
'# VAGRANT-END: 501 ac5b2706-6ca2-45b8-94ad-3d5bfc4151e0

**Comment by YungSang** [comment]
@nireak Hmm. That looks good...

**Comment by YungSang** [comment]
@nireak
It seems a sort of networking problem. Could you try another IP address for private_network?

**Comment by nireak** [comment]
@YungSang 
Thanks...
Yes, If I switch to other sub-net (for instance at vboxnet0 that has ip 192.168.33.1)
config.vm.network "private_network", ip: "192.168.33.10"
...it works ok!

So, as you said, it must be some kind of networking conflict.

Thank you

**Comment by YungSang** [comment]
@nireak You're welcome.
