### ISSUE TITLE
Folder not persistant after reboot

### ISSUE THREAD

**Issue by nireak** [YungSang/boot2docker-vagrant-box#6]
Hi again,

I have the following minimal Vagrantfile

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.3"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/boot2docker"

  config.vm.network "private_network", ip: "192.168.33.10"

  # Create data root dir
  config.vm.provision :shell, :inline => "mkdir -p /var/data"

end

The first time I boot the VM, I can ssh and I can find the "/var/data" directory. But, after a vagrant halt and up (without provisioning) ....the "/var/data" folder disappears...until a new provisioning is made.

Am I doing something wrong?

Thank you very much,

**Comment by YungSang** [comment]
A boot2docker VM is booted from the boot2docker.iso LiveCD, so that most of data in it is not persistent except an HDD storage for Docker.
You can use the HDD mounted at /mnt/sda for that.

```
config.vm.provision :shell, :inline => "mkdir -p /mnt/sda/var/data"
```

**Comment by YungSang** [comment]
Note: `vagrant halt` is OK, but `vagrant destroy` will destroy everything in the VM.

**Comment by nireak** [comment]
Thank you for you quick and accurate answer! Now I can persist data after a VM halt using the HDD mounted directory you pointed me. Best regards

**Comment by YungSang** [comment]
Thank you for using my distribution, btw. :)

**Comment by YungSang** [comment]
Since v1.3.2, the persist data disk has been changed `/mnt/sda` to `/mnt/sda1` due to fixing 42 layers issue of AUFS.

**Comment by nireak** [comment]
Thank you for the warning.

Is there any easy way to upgrade and preserve its current contents internally (without resorting to some external directory)? Like, for instance: 1.- Boot with version 1.3.4, 2.- Create /mnt/sda1, 3.- Move contents, 4.- Upgrade to yungsang/boot2docker 1.3.5?? I'm currently using yungsang/boot2docker 1.3.4 with docker 1.3.1. Thank you.

**Comment by YungSang** [comment]
Differences between v.1.3.4 and v1.3.5 are boot2docker.iso and the disk size.
So replacing boot2docker.iso should be fine.

```
$ vagrant halt
```

For Mac;

```
$ cd ~/.vagrant.d/boxes/yungsang-VAGRANTSLASH-boot2docker/1.3.4/virtualbox
$ cp boot2docker.iso boot2docker-1.3.4.iso
$ cp ../../1.3.5/virtualbox/boot2docker.iso .
```

```
$ vagrant up
```

I think that this is the easiest way.

Or you may replace the disk in between v1.3.4 and v1.3.5 instances(VMs in VirtualBox) (**not in the boxes**).

**Comment by nireak** [comment]
Thank you again!

I followed your instructions and it worked perfectly.  :)

**Comment by YungSang** [comment]
@nireak You're welcome. :)
