### ISSUE TITLE
Containers are not auto restarted after vagrant halt/vagrant up

### ISSUE THREAD

**Issue by alex-sherwin** [YungSang/boot2docker-vagrant-box#7]
The docker daemon is run as 

`/usr/local/bin/docker -d -D -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2375`

The default setting for the daemon docs say that --restart=true, but after vagrant halt/vagrant up, the previously running containers are not automatically restarted

**Comment by YungSang** [comment]
I checked it with the original boot2docker.iso through boot2docker-cli (down/up).
It has the same behavior.
I believe this is not a Vagrant-specific issue.

Could you open this issue at https://github.com/boot2docker/boot2docker ?

**Comment by alex-sherwin** [comment]
https://github.com/boot2docker/boot2docker/issues/423

**Comment by YungSang** [comment]
Fixed at v1.1.2.
https://github.com/boot2docker/boot2docker/issues/423#issuecomment-50198199
