### ISSUE TITLE
docker-enter missing

### ISSUE THREAD

**Issue by alex-sherwin** [YungSang/boot2docker-vagrant-box#8]
files/docker-enter was deleted in 38c265fb732eb4e6ec799d206baa5c66207d252a, but is still referred to in the packer template.json

**Comment by alex-sherwin** [comment]
scratch that.. your makefile pulls it

**Comment by YungSang** [comment]
I just uploaded my build of boot2docker.iso with nsenter.
https://github.com/YungSang/boot2docker/releases/tag/yungsang%2Fv1.1.1
It should work.

**Comment by YungSang** [comment]
Oops. It seems that you don't need my build.

**Comment by alex-sherwin** [comment]
Unfortunately no, I'm trying to get my own going for the vmware_workstation provider... figuring out how to follow your packer/vagrant workflow.

**Comment by YungSang** [comment]
FYI:
https://github.com/BenPhegan/boot2docker-vagrant-box
 He is also trying it.

**Comment by alex-sherwin** [comment]
Thanks, looks like he did pretty much the exact same things I did.  What I'm trying to do is simply:
1. use packer to process boot2docker.iso and apply the same logic as yours (configure the ext4 filesystem, and update a few files)
2. use packer vagrant post-processor to create a boot2docker-vmware.vbox 
3. spin up a new vagrant VM using boot2docker-vmware.vbox

If I take out the vagrant post-processor, which leaves the raw vmware VM (vmx/vmdk's etc), and manually boot up this VM, I can see everything worked 100% fine.. the 40GB filesystem is mounted etc.

However, if I leave the vagrant post-processor, which is only supposed to compress them all into a Vagrant vbox file, and use Vagrant to spin up a new VM... all my changes are lost.  The ext4 filesystem is not formatted/mounted and the custom files/scripts that were copied are gone.

I know that the vmdk disk files in the vbox file are the same as the ones the working ones... so far can't figure out what I'm missing here

**Comment by YungSang** [comment]
Umm. I'm not sure what happens, but It seems he was successful with v1.0.1 and v1.1.0.
https://github.com/BenPhegan/boot2docker-vagrant-box/commit/47d247be1b3d2c7566bf5df1c618b96f34fc4d6b

His boxes are https://vagrantcloud.com/benphegan/boot2docker .
